import aboutusModel from "../models/aboutus.model";
import appstoreModel from "../models/appStore.model"
import countryModel from "../models/country.model";
import orderTrackingModel from "../models/order-tracking.model";
import returnPolicyModel from "../models/return-policy.model";


/**  
 * Seeding AppStore for footer
 */
export async function initAppstore() {
    const appstoreData = {
        address: "Unit 15, Osborne Mill Waddington Street Oldham Greater Manchester OL9 6QH",
        email: "jammycycles@yahoo.co.uk",
        phone: "0161 652 3258",
        image: {
            url: "http://localhost:8000/images/image-1684133450903.png"
        }
    }

    try {
        await appstoreModel.deleteMany();
        await appstoreModel.create(appstoreData);
        
    } catch (err) {
        console.log("Error while seed  Appstore")
    }
}

/**  
 * Seeding About-us for footer
 */
export async function initAboutus() {
    const aboutusData = {
        images: [
            {
                url: "http://localhost:8000/images/image-1684121184519.jpg"
            }
        ],
        text: `CT Bikes (formerly Polaris Bikes) ltd. was formed in 2000 by a family collaboration of former bike engineers and assemblers. The company has worked hard to develop its business and reputation, with a successful expansion to our new premises at Osborne Mill, Oldham in 2011.
        CT Bikes has always aimed to provide a wide range of bikes, parts and accessories at the best prices, whilst maintaining great customer service. With a long history in the bike industry, we have a wealth of knowledge and expertise and can advise on all aspects of your requirements.
        Please note that for your security, CT Bikes do not retain your payment card information. If you pay by paypal or credit/debit card by phone, the payment processors may retain your information. To find out more visit www.paypal.co.uk or www.firstdatams.co.uk
        Being a leading bike retailer allows us to stock an outstanding range of men’s, women’s and kids bikes in the latest designs. Within our range, you’ll find Many Brands Like Tiger bikes,Viking bikes,Barracuda bikes,bikes from Cuda and many more,  bike similar  in conparision to many Large Retailer for example Halford,  Decathalon, Sports Direct to name a few. Our range covers all the riding disciplines and has something for each and every rider, with mountain bikes, full suspension mountain bikesand gravel bikesfor off-road lovers, road bikesfor speed fanatics, BMX bikesfor tricksters and hybrid bikesor folding bikesideal city for commuting. We also stock some of the UK’s best electric bikes on the market from the likes of  Insync Bike, Raleigh and Lombardo. And because electric mountain bikes are now more readily available, it’s easier to find an e-bike that suits you and your riding style. With an integrated electric motor, electric bikes provide a reliable solution and more efficient solution for leisurely rides and daily commutes. If you are commuting, folding electric bikes are a great option, especially if you travel frequently with a rucksack or heavy luggage. The compact nature of these bikes means they are well-suited to busy journeys that feature public transport.

At C T Bikes , we also take pride in our range of kids bikes.It features some of the coolest designs from top brands such as Disney, Bobbin, Raleigh and Cuda. Our range includes boy’s, girl’s and unisex bikes for all age groups ranging from 2-10+ years. So if you’re on the lookout for your child’s first bike,you’ll find colourful designs and familiar movie and TV characters that your kids will love. And because they’re designed with little hands and feet in mind, most of our bikes feature stabilisers which can be removed once your son or daughter learns how to cycle. Also, we stock a great selection of junior bikes which bring adult levels of comfort, safety and performance. Their lightweight alloy frame means they are excellent for transporting and loading in and out of vehicles.
Let C T Bikes take care of all your bike repair and bike servicing needs .
What’s more, all bikes available online can be built by our team of experts at a Warehouse  Alternatively, experience our trusted delivery service to get your bike delivered to your home or work. And to ensure you’re fully kitted out your cycling adventure, check out our range of cycling accessories .
        `,
    }

    try {
        await aboutusModel.deleteMany();
        await aboutusModel.create(aboutusData);
        
    } catch (err) {
        console.log("Error while seed  Aboutus")
    }
}

/**  
 * Seeding ReturnPolicy for footer
 */
export async function initReturnPolicy() {
    const data = {
        text: ` 14 day return policy applies from the date the item is delivered, any damage must be reported within 24 hours. Otherwise we will not be able to exchange the item.
All exchanges will be made within 4-14 working days basis once item is received.
Any unwanted items ordered must be returned at buyers expense and will be charged 10% handling fee.
The cancellation period only applies to goods that are unused, 7 day cancellation period applies.
If the item has been used we don’t accept returns.
If the product is faulty and the fault has been verified,  we will decide to refund or repair at our discretion, as our right under sales of goods act.
If you wish to cancel your purchase under distance selling regulations you must notify us in writing through email.
The bikes need to be assembled by professional cycle mechanics to keep the warranty, we will not be held responsible for incorrect assembly.
        `
    }

    try {
        await returnPolicyModel.deleteMany();
        await returnPolicyModel.create(data);
       
    } catch (err) {
        console.log("Error while seed  Return Policy")
    }
}


/**  
 * Seeding OrderTracking for footer
 */
export async function initOrderTracking() {
    const data = {
        text: `Your Orders are Dispatched Within 72 Hours of Cleared Payments

        All Small Parcels are sent Via Royal Mail 2nd Class Signed For Service (Free)
        
        Larger Items are dispatched Via Fully Tracked Courier
        
        We Also offer Different Delivery UK Services click the Link UK Shipping and International Shipping on Request
        
        Once Dispatched you will recieve confirmation of the Courier and Tracking number via email.
        
        To Track your Order please us the Link provided Below
        
        Track your order
        
        List of courier companies:
        
        DHL Parcels UK
        Collect plus
        Parcelforce
        Hermes
        DPD
        Royal Mail
        Yodel
        `,
        images: [
            {
                url: ""
            }
        ]
    }

    try {
        await orderTrackingModel.deleteMany();
        await orderTrackingModel.create(data);
       
    } catch (err) {
        console.log("Error while seed  Return Policy")
    }
}



/**  
 * Seeding countries
 */
export async function initCountries() {
    let countries = [
        {
            name: "Afghanistan",
            states: [],
        },
        {
            name: "Åland Islands",
            states: [],
        },
        {
            name: "Albania",
            states: ["Berat", "Dibër", "Durrës", "Elbasan", "Fier", "Gjirokastër", "Korçë", "Kukës",
                "Lezhë", "Shkodër", "Tirana", "Vlorë"],
        },
        {
            name: "Algeria",
            states: [
                "Adrar",
                "Chlef",
                "Laghouat",
                "Oum El Bouaghi",
                "Batna",
                "Béjaïa",
                "Biskra",
                "Béchar",
                "Blida",
                "Bouira",
                "Tamanrasset",
                "Tébessa",
                "Tlemcen",
                "Tiaret",
                "Tizi Ouzou",
                "Alger",
                "Djelfa",
                "Jijel",
                "Sétif",
                "Saïda",
                "Skikda",
                "Sidi Bel Abbès",
                "Annaba",
                "Guelma",
                "Constantine",
                "Médéa",
                "Mostaganem",
                "M'Sila",
                "Mascara",
                "Ouargla",
                "Oran",
                "El Bayadh",
                "Illizi",
                "Bordj Bou Arréridj",
                "Boumerdès",
                "El Tarf",
                "Tindouf",
                "Tissemsilt",
                "El Oued",
                "Khenchela",
                "Souk Ahras",
                "Tipasa",
                "Mila",
                "Aïn Defla",
                "Naâma",
                "Aïn Témouchent",
                "Ghardaïa",
                "Relizane"],
        },
        {
            name: "American Samoa",
            states: [],
        },
        {
            name: "Andorra",
            states: [],
        },
        {
            name: "Angola",
            states: [
                "Bengo",
                "Benguela",
                "Bié",
                "Cabinda",
                "Cuando Cubango",
                "Cuanza Norte",
                "Cuanza Sul",
                "Cunene",
                "Huambo",
                "Huíla",
                "Luanda",
                "Lunda Norte",
                "Lunda Sul",
                "Malanje",
                "Moxico",
                "Namibe",
                "Uíge",
                "Zaire"],
        },
        {
            name: "Anguilla",
            states: [],
        },
        {
            name: "Antarctica",
            states: [],
        },
        {
            name: "Antigua and Barbuda",
            states: [],
        },
        {
            name: "Argentina",
            states: [
                "Buenos Aires",
                "Catamarca",
                "Chaco",
                "Chubut",
                "Córdoba",
                "Corrientes",
                "Entre Ríos",
                "Formosa",
                "Jujuy",
                "La Pampa",
                "La Rioja",
                "Mendoza",
                "Misiones",
                "Neuquén",
                "Río Negro",
                "Salta",
                "San Juan",
                "San Luis",
                "Santa Cruz",
                "Santa Fe",
                "Santiago del Estero",
                "Tierra del Fuego",
                "Tucumán"],
        },
        {
            name: "Armenia",
            states: [],
        },
        {
            name: "Aruba",
            states: [],
        },
        {
            name: "Australia",
            states: ["Australian Capital Territory", "Jervis Bay Territory", "New South Wales", "	Victoria", "Queensland", "Western Australia", "South Australia", "Northern Territory", "Tasmania"],
        },
        {
            name: "Austria",
            states: [],
        },
        {
            name: "Azerbaijan",
            states: [],
        },
        {
            name: "Bahamas",
            states: [],
        },
        {
            name: "Bahrain",
            states: [],
        },
        {
            name: "Bangladesh",
            states: ["Bagerhat",
                "Bandarban",
                "Barguna",
                "Barisal",
                "Bhola",
                "Bogra",
                "Brahmanbaria",
                "Chandpur",
                "Chapai Nawabganj",
                "Chittagong",
                "Chuadanga",
                "Comilla",
                "Cox's Bazar",
                "Dhaka",
                "Dinajpur",
                "Faridpur",
                "Feni",
                "Gaibandha",
                "Gazipur",
                "Gopalganj",
                "Habiganj",
                "Jamalpur",
                "Jessore",
                "Jhalokati",
                "Jhenaidah",
                "Joypurhat",
                "Khagrachhari",
                "Khulna",
                "Kishoreganj",
                "Kurigram",
                "Kushtia",
                "Lakshmipur",
                "Lalmonirhat",
                "Madaripur",
                "Magura",
                "Manikganj",
                "Meherpur",
                "Moulvibazar",
                "Munshiganj",
                "Mymensingh",
                "Naogaon",
                "Narail",
                "Narayanganj",
                "Narsingdi",
                "Natore",
                "Nawabganj",
                "Netrokona",
                "Nilphamari",
                "Noakhali",
                "Pabna",
                "Panchagarh",
                "Patuakhali",
                "Pirojpur",
                "Rajbari",
                "Rajshahi",
                "Rangamati",
                "Rangpur",
                "Satkhira",
                "Shariatpur",
                "Sherpur",
                "Sirajganj",
                "Sunamganj",
                "Sylhet",
                "Tangail",
                "Thakurgaon"],
        },
        {
            name: "Barbados",
            states: [],
        },
        {
            name: "Belarus",
            states: [],
        },
        {
            name: "Belau",
            states: [],
        },
        {
            name: "Belgium",
            states: [],
        },
        {
            name: "Belize",
            states: [],
        },
        {
            name: "Benin",
            states: ["Alibori",
                "Atakora",
                "Atlantique",
                "Borgou",
                "Collines",
                "Kouffo",
                "Donga",
                "Littoral",
                "Mono",
                "Oueme",
                "Plateau",
                "Zou"],
        },
        {
            name: "Bermuda",
            states: [],
        },
        {
            name: "Bhutan",
            states: [],
        },
        {
            name: "Bolivia",
            states: ["Chuquisaca",
                "Cochabamba",
                "Beni",
                "La Paz",
                "Oruro",
                "Pando",
                "Potosí",
                "Santa Cruz",
                "Tarija"],
        },
        {
            name: "Bonaire, Saint Eustatius and Saba",
            states: [],
        },
        {
            name: "Bosnia and Herzegovina",
            states: [],
        },
        {
            name: "Botswana",
            states: [],
        },
        {
            name: "Bouvet Island",
            states: [],
        },
        {
            name: "Brazil",
            states: ["Acre",
                "Alagoas",
                "Amapá",
                "Amazonas",
                "Bahia",
                "Ceará",
                "Distrito Federal",
                "Espírito Santo",
                "Goiás",
                "Maranhão",
                "Mato Grosso",
                "Mato Grosso do Sul",
                "Minas Gerais",
                "Pará",
                "Paraíba",
                "Paraná",
                "Pernambuco",
                "Piauí",
                "Rio de Janeiro",
                "Rio Grande do Norte",
                "Rio Grande do Sul",
                "Rondônia",
                "Roraima",
                "Santa Catarina",
                "São Paulo",
                "Sergipe",
                "Tocantins"],
        },
        {
            name: "British Indian Ocean Territory",
            states: [],
        },
        {
            name: "Brunei",
            states: [],
        },
        {
            name: "Bulgaria",
            states: ["Blagoevgrad",
                "Burgas",
                "Dobrich",
                "Gabrovo",
                "Haskovo",
                "Kardzhali",
                "Kyustendil",
                "Lovech",
                "Montana",
                "Pazardzhik",
                "Pernik",
                "Pleven",
                "Plovdiv",
                "Razgrad",
                "Ruse",
                "Shumen",
                "Silistra",
                "Sliven",
                "Smolyan",
                "Sofia City",
                "Sofia Province",
                "Stara Zagora",
                "Targovishte",
                "Varna",
                "Veliko Tarnovo",
                "Vidin",
                "Vratsa",
                "Yambol"],
        },
        {
            name: "Burkina Faso",
            states: [],
        },
        {
            name: "Burundi",
            states: [],
        },
        {
            name: "Cambodia",
            states: [],
        },
        {
            name: "Cameroon",
            states: [],
        },
        {
            name: "Canada",
            states: ["Alberta",
                "British Columbia",
                "Manitoba",
                "New Brunswick",
                "Newfoundland and Labrador",
                "Nova Scotia",
                "Nunavut",
                "Ontario",
                "Prince Edward Island",
                "Quebec",
                "Saskatchewan",
                "Yukon Territory"],
        },
        {
            name: "Cape Verde",
            states: [],
        },
        {
            name: "Cayman Islands",
            states: [],
        },
        {
            name: "Central African Republic",
            states: [],
        },
        {
            name: "Chad",
            states: [],
        },
        {
            name: "Chile",
            states: ["Arica y Parinacota",
                "Tarapacá",
                "Antofagasta",
                "Atacama",
                "Coquimbo",
                "Valparaíso",
                "Región Metropolitana de Santiago",
                "O'Higgins",
                "Maule",
                "Ñuble",
                "Biobío",
                "La Araucanía",
                "Los Ríos",
                "Los Lagos",
                "Aysén",
                "Magallanes y de la Antártica Chilena"],
        },
        {
            name: "China",
            states: ["Anhui",
                "Beijing",
                "Chongqing",
                "Fujian",
                "Gansu",
                "Guangdong",
                "Guangxi",
                "Guizhou",
                "Hainan",
                "Hebei",
                "Heilongjiang",
                "Henan",
                "Hong Kong",
                "Hubei",
                "Hunan",
                "Inner Mongolia",
                "Jiangsu",
                "Jiangxi",
                "Jilin",
                "Liaoning",
                "Macau",
                "Ningxia",
                "Qinghai",
                "Shaanxi",
                "Shandong",
                "Shanghai",
                "Shanxi",
                "Sichuan",
                "Tianjin",
                "Tibet",
                "Xinjiang",
                "Yunnan",
                "Zhejiang"],
        },
        {
            name: "Christmas Island",
            states: [],
        },
        {
            name: "Cocos (keeling) Islands",
            states: [],
        },
        {
            name: "Colombia",
            states: ["Amazonas",
                "Antioquia",
                "Arauca",
                "Atlántico",
                "Bolívar",
                "Boyacá",
                "Caldas",
                "Caquetá",
                "Casanare",
                "Cauca",
                "Cesar",
                "Chocó",
                "Córdoba",
                "Cundinamarca",
                "Guainía",
                "Guaviare",
                "Huila",
                "La Guajira",
                "Magdalena",
                "Meta",
                "Nariño",
                "Norte de Santander",
                "Putumayo",
                "Quindío",
                "Risaralda",
                "San Andrés y Providencia",
                "Santander",
                "Sucre",
                "Tolima",
                "Valle del Cauca",
                "Vaupés",
                "Vichada"],
        },
        {
            name: "Comoros",
            states: [],
        },
        {
            name: "Congo (Brazzaville)",
            states: [],
        },
        {
            name: "Congo (Kinshasa)",
            states: [],
        },
        {
            name: "Cook Islands",
            states: [],
        },
        {
            name: "Costa Rica",
            states: ["San José",
                "Alajuela",
                "Cartago",
                "Heredia",
                "Guanacaste",
                "Puntarenas",
                "Limón"],
        },
        {
            name: "Croatia",
            states: [],
        },
        {
            name: "cuba",
            states: [],
        },
        {
            name: "Curaçao",
            states: [],
        },
        {
            name: "Cyprus",
            states: [],
        },
        {
            name: "Czech Republic",
            states: [],
        },
        {
            name: "Denmark",
            states: [],
        },
        {
            name: "Djibouti",
            states: [],
        },
        {
            name: "Dominica",
            states: [],
        },
        {
            name: "Dominican Republic",
            states: ["Azua",
                "Bahoruco",
                "Barahona",
                "Dajabón",
                "Distrito Nacional",
                "Duarte",
                "Elías Piña",
                "El Seibo",
                "Espaillat",
                "Hato Mayor",
                "Hermanas Mirabal",
                "Independencia",
                "La Altagracia",
                "La Romana",
                "La Vega",
                "María Trinidad Sánchez",
                "Monseñor Nouel",
                "Monte Cristi",
                "Monte Plata",
                "Pedernales",
                "Peravia",
                "Puerto Plata",
                "Samaná",
                "San Cristóbal",
                "San José de Ocoa",
                "San Juan",
                "San Pedro de Macorís",
                "Sánchez Ramírez",
                "Santiago",
                "Santiago Rodríguez",
                "Santo Domingo",
                "Valverde"],
        },
        {
            name: "Ecuador",
            states: ["Azuay",
                "Bolívar",
                "Cañar",
                "Carchi",
                "Chimborazo",
                "Cotopaxi",
                "El Oro",
                "Esmeraldas",
                "Galápagos",
                "Guayas",
                "Imbabura",
                "Loja",
                "Los Ríos",
                "Manabí",
                "Morona-Santiago",
                "Napo",
                "Orellana",
                "Pastaza",
                "Pichincha",
                "Santa Elena",
                "Santo Domingo de los Tsáchilas",
                "Sucumbíos",
                "Tungurahua",
                "Zamora-Chinchipe"],
        },
        {
            name: "Egypt",
            states: ["Alexandria",
                "Aswan",
                "Asyut",
                "Beheira",
                "Beni Suef",
                "Cairo",
                "Dakahlia",
                "Damietta",
                "Faiyum",
                "Gharbia",
                "Giza",
                "Ismailia",
                "Kafr El Sheikh",
                "Luxor",
                "Matrouh",
                "Minya",
                "Monufia",
                "New Valley",
                "North Sinai",
                "Port Said",
                "Qalyubia",
                "Qena",
                "Red Sea",
                "Sharqia",
                "Sohag",
                "South Sinai",
                "Suez"],
        },
        {
            name: "EI Salvador",
            states: ["Ahuachapán",
                "Cabañas",
                "Chalatenango",
                "Cuscatlán",
                "La Libertad",
                "La Paz",
                "La Unión",
                "Morazán",
                "San Miguel",
                "San Salvador",
                "San Vicente",
                "Santa Ana",
                "Sonsonate",
                "Usulután"],
        },
        {
            name: "Equatorial Guinea",
            states: [],
        },
        {
            name: "Eritrea",
            states: [],
        },
        {
            name: "Estonia",
            states: [],
        },
        {
            name: "Eswatini",
            states: [],
        },
        {
            name: "Ethiopia",
            states: [],
        },
        {
            name: "Falkland Islands",
            states: [],
        },
        {
            name: "Faroe Islands",
            states: [],
        },
        {
            name: "Fiji",
            states: [],
        },
        {
            name: "Finland",
            states: [],
        },
        {
            name: "France",
            states: [],
        },
        {
            name: "French Guiana",
            states: [],
        },
        {
            name: "French Polynesia",
            states: [],
        },
        {
            name: "French Southern Territories",
            states: [],
        },
        {
            name: "Gabon",
            states: [],
        },
        {
            name: "Gambia",
            states: [],
        },
        {
            name: "Georgia",
            states: [],
        },
        {
            name: "Germany",
            states: ["Baden-Württemberg",
                "Bavaria (Bayern)",
                "Berlin",
                "Brandenburg",
                "Bremen",
                "Hamburg",
                "Hesse (Hessen)",
                "Lower Saxony (Niedersachsen)",
                "Mecklenburg-Vorpommern",
                "North Rhine-Westphalia (Nordrhein-Westfalen)",
                "Rhineland-Palatinate (Rheinland-Pfalz)",
                "Saarland",
                "Saxony (Sachsen)",
                "Saxony-Anhalt (Sachsen-Anhalt)",
                "Schleswig-Holstein",
                "Thuringia (Thüringen)"],
        },
        {
            name: "Ghana",
            states: ["Ashanti",
                "Brong-Ahafo",
                "Central",
                "Eastern",
                "Greater Accra",
                "Northern",
                "Upper East",
                "Upper West",
                "Volta",
                "Western"],
        },
        {
            name: "Gibraltar",
            states: [],
        },
        {
            name: "Greece",
            states: ["Attica",
                "Central Greece",
                "Central Macedonia",
                "Crete",
                "Eastern Macedonia and Thrace",
                "Epirus",
                "Ionian Islands",
                "North Aegean",
                "Peloponnese",
                "South Aegean",
                "Thessaly",
                "Western Greece",
                "Western Macedonia"],
        },
        {
            name: "Greenland",
            states: [],
        },
        {
            name: "Grenada",
            states: [],
        },
        {
            name: "Guadeloupe",
            states: [],
        },
        {
            name: "Guam",
            states: [],
        },
        {
            name: "Guatemala",
            states: ["Alta Verapaz",
                "Baja Verapaz",
                "Chimaltenango",
                "Chiquimula",
                "El Progreso",
                "Escuintla",
                "Guatemala",
                "Huehuetenango",
                "Izabal",
                "Jalapa",
                "Jutiapa",
                "Petén",
                "Quetzaltenango",
                "Quiché",
                "Retalhuleu",
                "Sacatepéquez",
                "San Marcos",
                "Santa Rosa",
                "Sololá",
                "Suchitepéquez",
                "Totonicapán",
                "Zacapa"],
        },
        {
            name: "Guernsey",
            states: [],
        },
        {
            name: "Guinea",
            states: [],
        },
        {
            name: "Guinea-Bissau",
            states: [],
        },
        {
            name: "Guyana",
            states: [],
        },
        {
            name: "Haiti",
            states: [],
        },
        {
            name: "Heard Island and McDonald Islands",
            states: [],
        },
        {
            name: "Honduras",
            states: ["Atlántida",
                "Choluteca",
                "Colón",
                "Comayagua",
                "Copán",
                "Cortés",
                "El Paraíso",
                "Francisco Morazán",
                "Gracias a Dios",
                "Intibucá",
                "Islas de la Bahía",
                "La Paz",
                "Lempira",
                "Ocotepeque",
                "Olancho",
                "Santa Bárbara",
                "Valle",
                "Yoro"],
        },
        {
            name: "Hong Kong",
            states: ["Hong Kong Islands", "Kowloon", "New Territories"],
        },
        {
            name: "Hungary",
            states: ["Bács-Kiskun",
                "Baranya",
                "Békés",
                "Békéscsaba (city with county rights)",
                "Borsod-Abaúj-Zemplén",
                "Budapest (capital city with county rights)",
                "Csongrád",
                "Debrecen (city with county rights)",
                "Dunaújváros (city with county rights)",
                "Eger (city with county rights)",
                "Érd (city with county rights)",
                "Fejér",
                "Győr (city with county rights)",
                "Győr-Moson-Sopron",
                "Hajdú-Bihar",
                "Heves",
                "Hódmezővásárhely (city with county rights)",
                "Jász-Nagykun-Szolnok",
                "Kaposvár (city with county rights)",
                "Kecskemét (city with county rights)",
                "Komárom-Esztergom",
                "Miskolc (city with county rights)",
                "Nagykanizsa (city with county rights)",
                "Nógrád",
                "Nyíregyháza (city with county rights)",
                "Pécs (city with county rights)",
                "Pest",
                "Salgótarján (city with county rights)",
                "Somogy",
                "Sopron (city with county rights)",
                "Szabolcs-Szatmár-Bereg",
                "Székesfehérvár (city with county rights)",
                "Szeged (city with county rights)",
                "Szekszárd (city with county rights)",
                "Szentendre (city with county rights)",
                "Szolnok (city with county rights)",
                "Szombathely (city with county rights)",
                "Tatabánya (city with county rights)",
                "Tolna",
                "Vas",
                "Veszprém",
                "Zala",
                "Zalaegerszeg (city with county rights)"],
        },
        {
            name: "Iceland",
            states: [],
        },
        {
            name: "India",
            states: ["Andaman and Nicobar Islands",
                "Andhra Pradesh",
                "Arunachal Pradesh",
                "Assam",
                "Bihar",
                "Chandigarh",
                "Chhattisgarh",
                "Dadra and Nagar Haveli",
                "Daman and Diu",
                "Delhi",
                "Goa",
                "Gujarat",
                "Haryana",
                "Himachal Pradesh",
                "Jammu and Kashmir",
                "Jharkhand",
                "Karnataka",
                "Kerala",
                "Ladakh",
                "Lakshadweep",
                "Madhya Pradesh",
                "Maharashtra",
                "Manipur",
                "Meghalaya",
                "Mizoram",
                "Nagaland",
                "Odisha",
                "Puducherry",
                "Punjab",
                "Rajasthan",
                "Sikkim",
                "Tamil Nadu",
                "Telangana",
                "Tripura",
                "Uttar Pradesh",
                "Uttarakhand",
                "West Bengal"],
        },
        {
            name: "Indonesia",
            states: ["Aceh",
                "Bali",
                "Bangka Belitung",
                "Banten",
                "Bengkulu",
                "Central Java (Jawa Tengah)",
                "Central Kalimantan (Kalimantan Tengah)",
                "Central Sulawesi (Sulawesi Tengah)",
                "East Java (Jawa Timur)",
                "East Kalimantan (Kalimantan Timur)",
                "East Nusa Tenggara (Nusa Tenggara Timur)",
                "Gorontalo",
                "Jakarta Special Capital Region (Daerah Khusus Ibukota Jakarta)",
                "Jambi",
                "Lampung",
                "Maluku",
                "North Kalimantan (Kalimantan Utara)",
                "North Maluku (Maluku Utara)",
                "North Sulawesi (Sulawesi Utara)",
                "North Sumatra (Sumatera Utara)",
                "Papua",
                "Riau",
                "Riau Islands (Kepulauan Riau)",
                "South Kalimantan (Kalimantan Selatan)",
                "South Sulawesi (Sulawesi Selatan)",
                "South Sumatra (Sumatera Selatan)",
                "Southeast Sulawesi (Sulawesi Tenggara)",
                "West Java (Jawa Barat)",
                "West Kalimantan (Kalimantan Barat)",
                "West Nusa Tenggara (Nusa Tenggara Barat)",
                "West Papua (Papua Barat)",
                "West Sulawesi (Sulawesi Barat)",
                "West Sumatra (Sumatera Barat)",
                "Yogyakarta Special Region (Daerah Istimewa Yogyakarta)"],
        },
        {
            name: "Iran",
            states: ["Alborz",
                "Ardabil",
                "Bushehr",
                "Chaharmahal and Bakhtiari",
                "East Azerbaijan",
                "Isfahan",
                "Fars",
                "Gilan",
                "Golestan",
                "Hamadan",
                "Hormozgan",
                "Ilam",
                "Kerman",
                "Kermanshah",
                "North Khorasan",
                "Razavi Khorasan",
                "South Khorasan",
                "Khuzestan",
                "Kohgiluyeh and Boyer-Ahmad",
                "Kurdistan",
                "Lorestan",
                "Markazi",
                "Mazandaran",
                "Qazvin",
                "Qom",
                "Semnan",
                "Sistan and Baluchestan",
                "Tehran",
                "West Azerbaijan",
                "Yazd",
                "Zanjan"],
        },
        {
            name: "Iraq",
            states: [],
        },
        {
            name: "Ireland",
            states: ["Carlow",
                "Cavan",
                "Clare",
                "Cork",
                "Donegal",
                "Dublin",
                "Galway",
                "Kerry",
                "Kildare",
                "Kilkenny",
                "Laois",
                "Leitrim",
                "Limerick",
                "Longford",
                "Louth",
                "Mayo",
                "Meath",
                "Monaghan",
                "Offaly",
                "Roscommon",
                "Sligo",
                "Tipperary",
                "Waterford",
                "Westmeath",
                "Wexford",
                "Wicklow"],
        },
        {
            name: "Isle of Man",
            states: [],
        },
        {
            name: "Israel",
            states: [],
        },
        {
            name: "Italy",
            states: ["Agrigento",
                "Alessandria",
                "Ancona",
                "Aosta",
                "Arezzo",
                "Ascoli Piceno",
                "Asti",
                "Avellino",
                "Bari",
                "Barletta-Andria-Trani",
                "Belluno",
                "Benevento",
                "Bergamo",
                "Biella",
                "Bologna",
                "Bolzano",
                "Brescia",
                "Brindisi",
                "Cagliari",
                "Caltanissetta",
                "Campobasso",
                "Carbonia-Iglesias",
                "Caserta",
                "Catania",
                "Catanzaro",
                "Chieti",
                "Como",
                "Cosenza",
                "Cremona",
                "Crotone",
                "Cuneo",
                "Enna",
                "Fermo",
                "Ferrara",
                "Florence",
                "Foggia",
                "Forlì-Cesena",
                "Frosinone",
                "Genoa",
                "Gorizia",
                "Grosseto",
                "Imperia",
                "Isernia",
                "La Spezia",
                "L'Aquila",
                "Latina",
                "Lecce",
                "Lecco",
                "Livorno",
                "Lodi",
                "Lucca",
                "Macerata",
                "Mantua",
                "Massa and Carrara",
                "Matera",
                "Medio Campidano",
                "Messina",
                "Milan",
                "Modena",
                "Monza and Brianza",
                "Naples",
                "Novara",
                "Nuoro",
                "Ogliastra",
                "Olbia-Tempio",
                "Oristano",
                "Padua",
                "Palermo",
                "Parma",
                "Pavia",
                "Perugia",
                "Pesaro and Urbino",
                "Pescara",
                "Piacenza",
                "Pisa",
                "Pistoia",
                "Pordenone",
                "Potenza",
                "Prato",
                "Ragusa",
                "Ravenna",
                "Reggio Calabria",
                "Reggio Emilia",
                "Rieti",
                "Rimini",
                "Rome",
                "Rovigo",
                "Salerno",
                "Sassari",
                "Savona",
                "Siena",
                "Sondrio",
                "Syracuse",
                "Taranto",
                "Teramo",
                "Terni",
                "Trapani",
                "Trento",
                "Treviso",
                "Trieste",
                "Turin",
                "Udine",
                "Varese",
                "Venice",
                "Verbano-Cusio-Ossola",
                "Vercelli",
                "Verona",
                "Vibo Valentia",
                "Vicenza",
                "Viterbo"],
        },
        {
            name: "Ivory Coast",
            states: [],
        },
        {
            name: "Jamaica",
            states: [],
        },
        {
            name: "Japan",
            states: ["Aichi",
                "Akita",
                "Aomori",
                "Chiba",
                "Ehime",
                "Fukui",
                "Fukuoka",
                "Fukushima",
                "Gifu",
                "Gunma",
                "Hiroshima",
                "Hokkaido",
                "Hyogo",
                "Ibaraki",
                "Ishikawa",
                "Iwate",
                "Kagawa",
                "Kagoshima",
                "Kanagawa",
                "Kochi",
                "Kumamoto",
                "Kyoto",
                "Mie",
                "Miyagi",
                "Miyazaki",
                "Nagano",
                "Nagasaki",
                "Nara",
                "Niigata",
                "Oita",
                "Okayama",
                "Okinawa",
                "Osaka",
                "Saga",
                "Saitama",
                "Shiga",
                "Shimane",
                "Shizuoka",
                "Tochigi",
                "Tokushima",
                "Tokyo",
                "Tottori",
                "Toyama",
                "Wakayama",
                "Yamagata",
                "Yamaguchi",
                "Yamanashi"],
        },
        {
            name: "Jersey",
            states: [],
        },
        {
            name: "Jordan",
            states: [],
        },
        {
            name: "Kazakhstan",
            states: [],
        },
        {
            name: "Kenya",
            states: ["Baringo",
                "Bomet",
                "Bungoma",
                "Busia",
                "Elgeyo-Marakwet",
                "Embu",
                "Garissa",
                "Homa Bay",
                "Isiolo",
                "Kajiado",
                "Kakamega",
                "Kericho",
                "Kiambu",
                "Kilifi",
                "Kirinyaga",
                "Kisii",
                "Kisumu",
                "Kitui",
                "Kwale",
                "Laikipia",
                "Lamu",
                "Machakos",
                "Makueni",
                "Mandera",
                "Marsabit",
                "Meru",
                "Migori",
                "Mombasa",
                "Murang'a",
                "Nairobi",
                "Nakuru",
                "Nandi",
                "Narok",
                "Nyamira",
                "Nyandarua",
                "Nyeri",
                "Samburu",
                "Siaya",
                "Taita-Taveta",
                "Tana River",
                "Tharaka-Nithi",
                "Trans Nzoia",
                "Turkana",
                "Uasin Gishu",
                "Vihiga",
                "Wajir",
                "West Pokot"],
        },
        {
            name: "Kiribati",
            states: [],
        },
        {
            name: "Kuwait",
            states: [],
        },
        {
            name: "Kyrgyzstan",
            states: [],
        },
        {
            name: "Laos",
            states: [],
        },
        {
            name: "Latvia",
            states: [],
        },
        {
            name: "Lebanon",
            states: [],
        },
        {
            name: "Lesotho",
            states: [],
        },
        {
            name: "Liberia",
            states: ["Bomi",
                "Bong",
                "Gbarpolu",
                "Grand Bassa",
                "Grand Cape Mount",
                "Grand Gedeh",
                "Grand Kru",
                "Lofa",
                "Margibi",
                "Maryland",
                "Montserrado",
                "Nimba",
                "River Cess",
                "River Gee",
                "Sinoe"],
        },
        {
            name: "Libya",
            states: [],
        },
        {
            name: "Liechtenstein",
            states: [],
        },
        {
            name: "Lithuania",
            states: [],
        },
        {
            name: "Luxembourg",
            states: [],
        },
        {
            name: "Macao",
            states: [],
        },
        {
            name: "Madagascar",
            states: [],
        },
        {
            name: "Malawi",
            states: [],
        },
        {
            name: "Malaysia",
            states: ["Johor",
                "Kedah",
                "Kelantan",
                "Malacca (Melaka)",
                "Negeri Sembilan",
                "Pahang",
                "Perak",
                "Perlis",
                "Penang (Pulau Pinang)",
                "Sabah",
                "Sarawak",
                "Selangor",
                "Terengganu",
                "Kuala Lumpur",
                "Labuan",
                "Putrajaya"],
        },
        {
            name: "Maldives",
            states: [],
        },
        {
            name: "Mali",
            states: [],
        },
        {
            name: "Malta",
            states: [],
        },
        {
            name: "Marshall Islands",
            states: [],
        },
        {
            name: "Martinique",
            states: [],
        },
        {
            name: "Mauritania",
            states: [],
        },
        {
            name: "Mauritius",
            states: [],
        },
        {
            name: "Mayotte",
            states: [],
        },
        {
            name: "Mexico",
            states: ["Aguascalientes",
                "Baja California",
                "Baja California Sur",
                "Campeche",
                "Chiapas",
                "Chihuahua",
                "Coahuila",
                "Colima",
                "Durango",
                "Guanajuato",
                "Guerrero",
                "Hidalgo",
                "Jalisco",
                "Mexico State",
                "Michoacán",
                "Morelos",
                "Nayarit",
                "Nuevo León",
                "Oaxaca",
                "Puebla",
                "Querétaro",
                "Quintana Roo",
                "San Luis Potosí",
                "Sinaloa",
                "Sonora",
                "Tabasco",
                "Tamaulipas",
                "Tlaxcala",
                "Veracruz",
                "Yucatán",
                "Zacatecas"],
        },
        {
            name: "Micronesia",
            states: [],
        },
        {
            name: "Moldova",
            states: ["Anenii Noi",
                "Basarabeasca",
                "Briceni",
                "Cahul",
                "Călărași",
                "Cantemir",
                "Căuşeni",
                "Chișinău",
                "Cimișlia",
                "Criuleni",
                "Dondușeni",
                "Drochia",
                "Dubăsari",
                "Edineț",
                "Fălești",
                "Florești",
                "Găgăuzia",
                "Glodeni",
                "Hîncești",
                "Ialoveni",
                "Leova",
                "Nisporeni",
                "Ocnița",
                "Orhei",
                "Rezina",
                "Rîșcani",
                "Sîngerei",
                "Șoldănești",
                "Soroca",
                "Stînga Nistrului",
                "Strășeni",
                "Taraclia",
                "Telenești",
                "Ungheni"],
        },
        {
            name: "Monaco",
            states: [],
        },
        {
            name: "Mongolia",
            states: [],
        },
        {
            name: "Montenegro",
            states: [],
        },
        {
            name: "Montserrat",
            states: [],
        },
        {
            name: "Morocco",
            states: [],
        },
        {
            name: "Mozambique",
            states: ["Cabo Delgado",
                "Gaza",
                "Inhambane",
                "Manica",
                "Maputo",
                "Nampula",
                "Niassa",
                "Sofala",
                "Tete",
                "Zambezia"],
        },
        {
            name: "Myanmar",
            states: [],
        },
        {
            name: "Namibia",
            states: ["Erongo",
                "Hardap",
                "Karas",
                "Kavango East",
                "Kavango West",
                "Khomas",
                "Kunene",
                "Ohangwena",
                "Omaheke",
                "Omusati",
                "Oshana",
                "Oshikoto",
                "Otjozondjupa",
                "Zambezi"],
        },
        {
            name: "Nauru",
            states: [],
        },
        {
            name: "Nepal",
            states: ["Bagmati", "Bheri", "Dhaulagiri", "Gandaki", "Janakpur", "Karnali", "Koshi", "Lumbini", "Mahakali", "Mechi", "Narayani", "Rapti", "Sagarmatha"
                , "Seti",],
        },
        {
            name: "Netherlands",
            states: [],
        },
        {
            name: "New Caledonia",
            states: [],
        },
        {
            name: "New Zealand",
            states: ["Northland",
                "Auckland",
                "Waikato",
                "Bay of Plenty",
                "Gisborne",
                "Hawke's Bay",
                "Taranaki",
                "Manawatu-Whanganui",
                "Wellington",
                "Tasman",
                "Nelson",
                "Marlborough",
                "West Coast",
                "Canterbury",
                "Otago",
                "Southland"],
        },
        {
            name: "Nicaragua",
            states: ["Boaco",
                "Carazo",
                "Chinandega",
                "Chontales",
                "Estelí",
                "Granada",
                "Jinotega",
                "León",
                "Madriz",
                "Managua",
                "Masaya",
                "Matagalpa",
                "Nueva Segovia",
                "Rivas",
                "Río San Juan",
                "RACCN (North Caribbean Coast Autonomous Region)",
                "RACCS (South Caribbean Coast Autonomous Region)"],
        },
        {
            name: "Niger",
            states: [],
        },
        {
            name: "Nigeria",
            states: ["Abia",
                "Adamawa",
                "Akwa Ibom",
                "Anambra",
                "Bauchi",
                "Bayelsa",
                "Benue",
                "Borno",
                "Cross River",
                "Delta",
                "Ebonyi",
                "Edo",
                "Ekiti",
                "Enugu",
                "Gombe",
                "Imo",
                "Jigawa",
                "Kaduna",
                "Kano",
                "Katsina",
                "Kebbi",
                "Kogi",
                "Kwara",
                "Lagos",
                "Nasarawa",
                "Niger",
                "Ogun",
                "Ondo",
                "Osun",
                "Oyo",
                "Plateau",
                "Rivers",
                "Sokoto",
                "Taraba",
                "Yobe",
                "Zamfara",
                "Federal Capital Territory (Abuja)"],
        },
        {
            name: "Niue",
            states: [],
        },
        {
            name: "Norfold Island",
            states: [],
        },
        {
            name: "North Korea",
            states: [],
        },
        {
            name: "North Macedonia",
            states: [],
        },
        {
            name: "Northern Mariana Islands",
            states: [],
        },
        {
            name: "Norway",
            states: [],
        },
        {
            name: "Oman",
            states: [],
        },
        {
            name: "Pakistan",
            states: ["Punjab",
                "Sindh",
                "Khyber Pakhtunkhwa",
                "Balochistan",
                "Gilgit-Baltistan",
                "Azad Jammu and Kashmir",
                "Islamabad Capital Territory"],
        },
        {
            name: "Palestinian Territory",
            states: [],
        },
        {
            name: "Panama",
            states: [],
        },
        {
            name: "Papua New Guinea",
            states: [],
        },
        {
            name: "Paraguay",
            states: [],
        },
        {
            name: "Peru",
            states: ["Amazonas",
                "Áncash",
                "Apurímac",
                "Arequipa",
                "Ayacucho",
                "Cajamarca",
                "Callao",
                "Cusco",
                "Huancavelica",
                "Huánuco",
                "Ica",
                "Junín",
                "La Libertad",
                "Lambayeque",
                "Lima",
                "Loreto",
                "Madre de Dios",
                "Moquegua",
                "Pasco",
                "Piura",
                "Puno",
                "San Martín",
                "Tacna",
                "Tumbes",
                "Ucayali"],
        },
        {
            name: "Philippines",
            states: ["Ilocos Region",
                "Cagayan Valley",
                "Central Luzon",
                "CALABARZON",
                "MIMAROPA",
                "Bicol Region",
                "Western Visayas",
                "Central Visayas",
                "Eastern Visayas",
                "Zamboanga Peninsula",
                "Northern Mindanao",
                "Davao Region",
                "SOCCSKSARGEN",
                "Caraga",
                "Bangsamoro Autonomous Region in Muslim Mindanao",
                "Cordillera Administrative Region",
                "National Capital Region"],
        },
        {
            name: "Pitcairn",
            states: [],
        },
        {
            name: "Poland",
            states: [],
        },
        {
            name: "Portugal",
            states: [],
        },
        {
            name: "Puerto Rico",
            states: [],
        },
        {
            name: "Qatar",
            states: [],
        },
        {
            name: "Reunion",
            states: [],
        },
        {
            name: "Romania",
            states: [],
        },
        {
            name: "Russia",
            states: [],
        },
        {
            name: "Rwanda",
            states: [],
        },
        {
            name: "São Tomé and Príncipe",
            states: [],
        },
        {
            name: "Saint Barthélemy",
            states: [],
        },
        {
            name: "Saint Helena",
            states: [],
        },
        {
            name: "Saint Kitts and Nevis",
            states: [],
        },
        {
            name: "Saint Lucia",
            states: [],
        },
        {
            name: "Saint Martin (Dutch part)",
            states: [],
        },
        {
            name: "Saint Martin (French part)",
            states: [],
        },
        {
            name: "Saint Pierre and Miquelon",
            states: [],
        },
        {
            name: "Saint Vincent and the Grenadines",
            states: [],
        },
        {
            name: "Samoa",
            states: [],
        },
        {
            name: "San Marino",
            states: [],
        },
        {
            name: "Saudi Arabia",
            states: [],
        },
        {
            name: "Senegal",
            states: ["Dakar",
                "Diourbel",
                "Fatick",
                "Kaolack",
                "Kédougou",
                "Kolda",
                "Louga",
                "Matam",
                "Saint-Louis",
                "Sédhiou",
                "Tambacounda",
                "Thiès",
                "Ziguinchor",
                "Kaffrine"],
        },
        {
            name: "Serbia",
            states: ["Belgrade",
                "Bor",
                "Braničevo",
                "Jablanica",
                "Kolubara",
                "Mačva",
                "Moravica",
                "Nišava",
                "Pčinja",
                "Peć",
                "Pirot",
                "Podunavlje",
                "Pomoravlje",
                "Rasina",
                "Raška",
                "Severna Bačka",
                "Severni Banat",
                "Srednji Banat",
                "Šumadija",
                "Toplica",
                "Zaječar",
                "Zapadna Bačka",
                "Zlatibor",
                "Južna Bačka",
                "Južni Banat",
                "Kosovo-Pomoravlje",
                "Kosovska Mitrovica",
                "Kosovski",
                "Pećki"],
        },
        {
            name: "Seychelles",
            states: [],
        },
        {
            name: "Sierra Leone",
            states: [],
        },
        {
            name: "Singapore",
            states: [],
        },
        {
            name: "Slovakia",
            states: [],
        },
        {
            name: "Slovenia",
            states: [],
        },
        {
            name: "Solomon Islands",
            states: [],
        },
        {
            name: "Somalia",
            states: [],
        },
        {
            name: "South Africa",
            states: ["Eastern Cape",
                "Free State",
                "Gauteng",
                "KwaZulu-Natal",
                "Limpopo",
                "Mpumalanga",
                "Northern Cape",
                "North West",
                "Western Cape"],
        },
        {
            name: "South Georgia/Sandwich Islands",
            states: [],
        },
        {
            name: "South Korea",
            states: [],
        },
        {
            name: "South Sudan",
            states: [],
        },
        {
            name: "Spain",
            states: ["Andalusia",
            "Aragon",
            "Asturias",
            "Balearic Islands",
            "Basque Country",
            "Canary Islands",
            "Cantabria",
            "Castilla-La Mancha",
            "Castilla y León",
            "Catalonia",
            "Extremadura",
            "Galicia",
            "La Rioja",
            "Madrid",
            "Murcia",
            "Navarre",
            "Valencian Community"],
        },
        {
            name: "Sri Lanka",
            states: [],
        },
        {
            name: "Sudan",
            states: [],
        },
        {
            name: "Suriname",
            states: [],
        },
        {
            name: "Svalbard and Jan Mayen",
            states: [],
        },
        {
            name: "Sweden",
            states: [],
        },
        {
            name: "Switzerland",
            states: ["Aargau",
            "Appenzell Ausserrhoden",
            "Appenzell Innerrhoden",
            "Basel-Landschaft",
            "Basel-Stadt",
            "Bern",
            "Fribourg",
            "Geneva",
            "Glarus",
            "Graubünden",
            "Jura",
            "Lucerne",
            "Neuchâtel",
            "Nidwalden",
            "Obwalden",
            "Schaffhausen",
            "Schwyz",
            "Solothurn",
            "St. Gallen",
            "Thurgau",
            "Ticino",
            "Uri",
            "Valais",
            "Vaud",
            "Zug",
            "Zurich"],
        },
        {
            name: "Syria",
            states: [],
        },
        {
            name: "Taiwan",
            states: [],
        },
        {
            name: "Tajikistan",
            states: [],
        },
        {
            name: "Tanzania",
            states: ["Arusha",
            "Dar es Salaam",
            "Dodoma",
            "Geita",
            "Iringa",
            "Kagera",
            "Katavi",
            "Kigoma",
            "Kilimanjaro",
            "Lindi",
            "Manyara",
            "Mara",
            "Mbeya",
            "Morogoro",
            "Mtwara",
            "Mwanza",
            "Njombe",
            "Pemba North",
            "Pemba South",
            "Pwani",
            "Rukwa",
            "Ruvuma",
            "Shinyanga",
            "Simiyu",
            "Singida",
            "Songwe",
            "Tabora",
            "Tanga",
            "Zanzibar Central/South",
            "Zanzibar North",
            "Zanzibar Urban/West",],
        },
        {
            name: "Thailand",
            states: [ "Amnat Charoen",
            "Ang Thong",
            "Bangkok",
            "Bueng Kan",
            "Buri Ram",
            "Chachoengsao",
            "Chai Nat",
            "Chaiyaphum",
            "Chanthaburi",
            "Chiang Mai",
            "Chiang Rai",
            "Chon Buri",
            "Chumphon",
            "Kalasin",
            "Kamphaeng Phet",
            "Kanchanaburi",
            "Khon Kaen",
            "Krabi",
            "Lampang",
            "Lamphun",
            "Loei",
            "Lopburi",
            "Mae Hong Son",
            "Maha Sarakham",
            "Mukdahan",
            "Nakhon Nayok",
            "Nakhon Pathom",
            "Nakhon Phanom",
            "Nakhon Ratchasima",
            "Nakhon Sawan",
            "Nakhon Si Thammarat",
            "Nan",
            "Narathiwat",
            "Nong Bua Lamphu",
            "Nong Khai",
            "Nonthaburi",
            "Pathum Thani",
            "Pattani",
            "Phang Nga",
            "Phatthalung",
            "Phayao",
            "Phetchabun",
            "Phetchaburi",
            "Phichit",
            "Phitsanulok",
            "Phra Nakhon Si Ayutthaya",
            "Phrae",
            "Phuket",
            "Prachinburi",
            "Prachuap Khiri Khan",
            "Ranong",
            "Ratchaburi",
            "Rayong",
            "Roi Et",
            "Sa Kaeo",
            "Sakon Nakhon",
            "Samut Prakan",
            "Samut Sakhon",
            "Samut Songkhram",
            "Saraburi",
            "Satun",
            "Si Sa Ket",
            "Sing Buri",
            "Songkhla",
            "Sukhothai",
            "Suphan Buri",
            "Surat Thani",
            "Surin",
            "Tak",
            "Trang",
            "Trat",
            "Ubon Ratchathani",
            "Udon Thani",
            "Uthai Thani",
            "Uttaradit",
            "Yala",
            "Yasothon"],
        },
        {
            name: "Timor-Leste",
            states: [],
        },
        {
            name: "Togo",
            states: [],
        },
        {
            name: "Tokelau",
            states: [],
        },
        {
            name: "Tonga",
            states: [],
        },
        {
            name: "Trinidad and Tobago",
            states: [],
        },
        {
            name: "Tunisia",
            states: [],
        },
        {
            name: "Turkey",
            states: [ "Adana",
            "Adıyaman",
            "Afyonkarahisar",
            "Ağrı",
            "Aksaray",
            "Amasya",
            "Ankara",
            "Antalya",
            "Ardahan",
            "Artvin",
            "Aydın",
            "Balıkesir",
            "Bartın",
            "Batman",
            "Bayburt",
            "Bilecik",
            "Bingöl",
            "Bitlis",
            "Bolu",
            "Burdur",
            "Bursa",
            "Çanakkale",
            "Çankırı",
            "Çorum",
            "Denizli",
            "Diyarbakır",
            "Düzce",
            "Edirne",
            "Elazığ",
            "Erzincan",
            "Erzurum",
            "Eskişehir",
            "Gaziantep",
            "Giresun",
            "Gümüşhane",
            "Hakkâri",
            "Hatay",
            "Iğdır",
            "Isparta",
            "İstanbul",
            "İzmir",
            "Kahramanmaraş",
            "Karabük",
            "Karaman",
            "Kars",
            "Kastamonu",
            "Kayseri",
            "Kırıkkale",
            "Kırklareli",
            "Kırşehir",
            "Kilis",
            "Kocaeli",
            "Konya",
            "Kütahya",
            "Malatya",
            "Manisa",
            "Mardin",
            "Mersin",
            "Muğla",
            "Muş",
            "Nevşehir",
            "Niğde",
            "Ordu",
            "Osmaniye",
            "Rize",
            "Sakarya",
            "Samsun",
            "Siirt",
            "Sinop",
            "Sivas",
            "Şanlıurfa",
            "Şırnak",
            "Tekirdağ",
            "Tokat",
            "Trabzon",
            "Tunceli",
            "Uşak",
            "Van",
            "Yalova",
            "Yozgat",
            "Zonguldak"],
        },
        {
            name: "Turkmenistan",
            states: [],
        },
        {
            name: "Turks and Caicos Islands",
            states: [],
        },
        {
            name: "Tuvalu",
            states: [],
        },
        {
            name: "Uganda",
            states: [],
        },
        {
            name: "Ukraine",
            states: ["Vinnytsia",
            "Volyn",
            "Dnipropetrovsk",
            "Donetsk",
            "Zhytomyr",
            "Zakarpattia",
            "Zaporizhia",
            "Ivano-Frankivsk",
            "Kyiv",
            "Kirovohrad",
            "Luhansk",
            "Lviv",
            "Mykolaiv",
            "Odessa",
            "Poltava",
            "Rivne",
            "Sumy",
            "Ternopil",
            "Kharkiv",
            "Kherson",
            "Khmelnytskyi",
            "Cherkasy",
            "Chernihiv",
            "Chernivtsi",
            "Crimea (Autonomous Republic)"],
        },
        {
            name: "United Arabs Emirates",
            states: [],
        },
        {
            name: "United Kingdom (UK)",
            states: [],
        },
        {
            name: "United States (US)",
            states: ["Alabama",
            "Alaska",
            "Arizona",
            "Arkansas",
            "California",
            "Colorado",
            "Connecticut",
            "Delaware",
            "Florida",
            "Georgia",
            "Hawaii",
            "Idaho",
            "Illinois",
            "Indiana",
            "Iowa",
            "Kansas",
            "Kentucky",
            "Louisiana",
            "Maine",
            "Maryland",
            "Massachusetts",
            "Michigan",
            "Minnesota",
            "Mississippi",
            "Missouri",
            "Montana",
            "Nebraska",
            "Nevada",
            "New Hampshire",
            "New Jersey",
            "New Mexico",
            "New York",
            "North Carolina",
            "North Dakota",
            "Ohio",
            "Oklahoma",
            "Oregon",
            "Pennsylvania",
            "Rhode Island",
            "South Carolina",
            "South Dakota",
            "Tennessee",
            "Texas",
            "Utah",
            "Vermont",
            "Virginia",
            "Washington",
            "West Virginia",
            "Wisconsin",
            "Wyoming"],
        },
        {
            name: "United States (US) Minor Outlying Islands",
            states: ["Baker Island",
            "Howland Island",
            "Jarvis Island",
            "Johnston Atoll",
            "Kingman Reef",
            "Midway Atoll",
            "Navassa Island",
            "Palmyra Atoll",
            "Wake Island"],
        },
        {
            name: "Uruguay",
            states: [ "Artigas",
            "Canelones",
            "Cerro Largo",
            "Colonia",
            "Durazno",
            "Flores",
            "Florida",
            "Lavalleja",
            "Maldonado",
            "Montevideo",
            "Paysandú",
            "Río Negro",
            "Rivera",
            "Rocha",
            "Salto",
            "San José",
            "Soriano",
            "Tacuarembó",
            "Treinta y Tres"],
        },
        {
            name: "Uzbekistan",
            states: [],
        },
        {
            name: "Vanuatu",
            states: [],
        },
        {
            name: "Vatican",
            states: [],
        },
        {
            name: "Venezuela",
            states: [ "Amazonas",
            "Anzoátegui",
            "Apure",
            "Aragua",
            "Barinas",
            "Bolívar",
            "Carabobo",
            "Cojedes",
            "Delta Amacuro",
            "Falcón",
            "Guárico",
            "Lara",
            "Mérida",
            "Miranda",
            "Monagas",
            "Nueva Esparta",
            "Portuguesa",
            "Sucre",
            "Táchira",
            "Trujillo",
            "Vargas",
            "Yaracuy",
            "Zulia",
            "Capital District"],
        },
        {
            name: "Vietnam",
            states: [],
        },
        {
            name: "Virgin Islands (British)",
            states: [],
        },
        {
            name: "Virgin Islands (US)",
            states: [],
        },
        {
            name: "Wallis and Futuna",
            states: [],
        },
        {
            name: "Western Sahara",
            states: [],
        },
        {
            name: "Yemen",
            states: [],
        },
        {
            name: "Zambia",
            states: ["Central",
            "Copperbelt",
            "Eastern",
            "Luapula",
            "Lusaka",
            "Muchinga",
            "Northern",
            "North-Western",
            "Southern",
            "Western"],
        },
        {
            name: "Zimbabwe",
            states: [],
        },
       
       
       
       
       
       
       
    ]

    try {
        await countryModel.deleteMany();
        for(let i of countries){

            await countryModel.create(i);
        }
       
    } catch (err) {
        console.log("Error while seed  Countries")
    }
}